name: Build & push base image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/coder/envbuilder
      env:
        ENVBUILDER_WORKSPACE_FOLDER: ${{ github.workspace }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

      - name: "Build devcontainer"
        run: envbuilder
